project_name: gophercon-turkey-2021
before:
  hooks:
    - go mod tidy
  

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.build={{.ShortCommit}}
    no_unique_dist_dir: true
    binary: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'

archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    format: binary

dockers:
  - image_templates:
      - gophercon/gophercon-turkey-2021:{{.Version}}
    dockerfile: Dockerfile.goreleaser
